In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Create a sample DataFrame
data = {'Color': ['Red', 'Green', 'Blue', 'Red', 'Blue'],
        'Size': ['Small', 'Large', 'Medium', 'Medium', 'Small']}
df = pd.DataFrame(data)

# Select the columns to convert to 'category' data type
columns_to_convert = ['Color', 'Size']

encoder = OrdinalEncoder()
encoder.fit(df[columns_to_convert])
encoded_values = encoder.transform(df[columns_to_convert])

# Replace the original columns with the encoded values
for i, col in enumerate(columns_to_convert):
    df[col] = encoded_values[:, i]#.astype(int)

df

   Color  Size
0    2.0   2.0
1    1.0   0.0
2    0.0   1.0
3    2.0   1.0
4    0.0   2.0

In [20]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder
from sklearn.feature_extraction import DictVectorizer

# Sample data with categorical variables
data = {
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Shape': ['Circle', 'Square', 'Triangle', 'Circle', 'Square']
}
df = pd.DataFrame(data)
# Using OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
ordinal_encoded = ordinal_encoder.fit_transform(df)
# print("Ordinal Encoded Data:")
# print(ordinal_encoded)

# Using LabelEncoder
label_encoder = LabelEncoder()
label_encoded = df.apply(label_encoder.fit_transform)
# print("\nLabel Encoded Data:")
# print(label_encoded)

# Using OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(df)
print("\nOne-Hot Encoded Data:")
print(onehot_encoded)

# Using pd.get_dummies
dummies_encoded = pd.get_dummies(df)
print("\nDummy Encoded Data:")
print(dummies_encoded)

# Using DictVectorizer
dict_encoder = DictVectorizer(sparse=False)
dict_encoded = dict_encoder.fit_transform(df.to_dict(orient='records'))
print("\nDict Encoded Data:")
print(dict_encoded)
df

One-Hot Encoded Data:
[[0. 0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1. 0.]]

Dummy Encoded Data:
   Color_Blue  Color_Green  Color_Red  Size_Large  Size_Medium  Size_Small  \
0           0            0          1           0            0           1
1           1            0          0           1            0           0
2           0            1          0           0            1           0
3           0            0          1           1            0           0
4           1            0          0           0            0           1

   Shape_Circle  Shape_Square  Shape_Triangle
0             1             0               0
1             0             1               0
2             0             0               1
3             1             0               0
4             0             1               0

Dict Encoded Data:
[[0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1.]]

c:\Users\Aryan.ABSALAN\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

   Color    Size     Shape
0    Red   Small    Circle
1   Blue   Large    Square
2  Green  Medium  Triangle
3    Red   Large    Circle
4   Blue   Small    Square

In [23]:
# Concatenate the original DataFrame and encoded dummy variables
df_encoded = pd.concat([df, dummies_encoded], axis=1)
df_encoded

,Color,Size,Shape,Color_Blue,Color_Green,Color_Red,Size_Large,Size_Medium,Size_Small,Shape_Circle,Shape_Square,Shape_Triangle
0,Red,Small,Circle,0,0,1,0,0,1,1,0,0
1,Blue,Large,Square,1,0,0,1,0,0,0,1,0
2,Green,Medium,Triangle,0,1,0,0,1,0,0,0,1
3,Red,Large,Circle,0,0,1,1,0,0,1,0,0
4,Blue,Small,Square,1,0,0,0,0,1,0,1,0