In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import  accuracy_score

"""
These are some of the most important parameters for building a Decision Tree Regression.

It's recommended to experiment with different parameter values 
and use techniques like cross-validation 
to find the optimal set of parameters for your specific problem.
"""

# Load the Iris dataset
data = load_iris()

# Split the dataset into features (X) and target variable (y)
X = data.data
y = data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Decision Tree Classifier
model = DecisionTreeClassifier()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 1.0

In [10]:
import pandas as pd

# Create a DataFrame from the diabetes dataset for the features and target variable
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# Display the DataFrame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [11]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [27]:
from sklearn.metrics import r2_score, mean_squared_error

"""
It's recommended to experiment with different parameter values 
and use techniques like cross-validation 
to find the optimal set of parameters for your specific problem.
"""
# Create a Decision Tree Classifier with custom parameter values
model_custom_parameter_values = DecisionTreeClassifier(max_depth=3, min_samples_split=5, max_features=2)
model_custom_parameter_values_2nd = DecisionTreeClassifier(max_depth=3, min_samples_split=5, max_features=3)

# Fit the model to the training data
model_custom_parameter_values.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model_custom_parameter_values.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

# Calculate the R2 score of the model
r2_score = r2_score(y_test, y_pred)
print("R2 Score:", r2_score)

# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)


# Fit the model_custom_parameter_values_2nd to the training data
model_custom_parameter_values_2nd.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model_custom_parameter_values_2nd.predict(X_test)

# Calculate the accuracy score
accuracy_2nd = accuracy_score(y_test, y_pred)
print("Accuracy Score_2nd:", accuracy_2nd)

# Calculate the mean squared error (MSE)
mse_2nd = mean_squared_error(y_test, y_pred)
print("Mean Squared Error_2nd:", mse_2nd)

Accuracy Score: 1.0
R2 Score: 1.0
Mean Squared Error: 0.0
Accuracy Score_2nd: 1.0
Mean Squared Error_2nd: 0.0